### ISSUE TITLE
Compiling on Platformio / ESP-IDF

### ISSUE THREAD

**Issue by tertomium** [fl4p/fugu-mppt-firmware#11]
Hey there,
trying to build the project on platformio.
cloned the "main" repo using git console, opened the folder in platformio as a project.
I have issues with littlefs config files, since i2c/lcd isnt working:
`252][W][esp32-hal-psram.c:71] psramInit(): PSRAM init failed!
[   275][V][esp32-hal-uart.c:330] uartBegin(): UART0 baud(115200) Mode(800001c) rxPin(44) txPin(43)
[   284][V][esp32-hal-uart.c:416] uartBegin(): UART0 not installed. Starting installation
[   293][V][esp32-hal-uart.c:463] uartBegin(): UART0 initialization done.
[   300][I][main.cpp:193] setup(): [main] *** Fugu Firmware Version 2.1.0 (Jul 10 2024 11:12:00)
[   337][E][main.cpp:221] setup(): [main] error during sensor setup: no sensor conf
[   345][I][buck.h:49] init(): [buck] pwmDriver.pwmMax=2047, pwmMinLS=123, pwmMinHS=30, pwmMaxHS=1924
[   363][I][store.h:130] load(): [store] File /littlefs/daily doesn't exists (unable to stat)
[   372][I][metering.h:222] load(): [mppt] Restored stats: totalEnergy=0.00 bootCounter=10 dailyEnergyMeter=0.00
[   395][I][store.h:179] update(): [store] Wrote /littlefs/stats (size 24)
[   402][I][store.h:239] update(): [flash] Wrote flash value /littlefs/stats
[   409][I][mppt.h:344] startSweep(): [mppt] Start sweep
[   414][I][sampling.h:195] startCalibration(): [mppt] Start calibration
[   421][I][main.cpp:250] setup(): [main] setup() done.`

Adding a wifi leads to:
`
wifi-add FRITZ!Box_WLAN_3131:3312500380897585
[ 93653][I][main.cpp:491] handleCommand(): [main] received serial command: 'wifi-add FRITZ!Box_WLAN_3131:3312500380897585'
[ 93665][I][main.cpp:549] handleCommand(): [main] adding wifi network FRITZ!Box_WLAN_3131 (psk=XXXXXXXX)
[ 93681][E][store.h:306] add(): [store] Cannot write /littlefs/conf/wifi

assert failed: void ConfFile::add(const std::unordered_map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >&) store.h:308 (f != nullptr)

Backtrace: 0x403781fa:0x3fceb7d0 0x4037d58d:0x3fceb7f0 0x40383621:0x3fceb810 0x420086e7:0x3fceb940 0x42009901:0x3fceb9c0 0x4200a022:0x3fcebad0 0x4200a219:0x3fcebb70 0x4200d023:0x3fcebbd0 0x4201a171:0x3fcebc00
`
Do i put the config files into data/littlefs/conf folder?
What do I miss here?

edit: 
Got it. Files go straight into data/conf/
Had to adapt my sensor files upper and lower resistors to get valid readings.

**Comment by fl4p** [comment]
Hi,

I've added instructions on how to flash the configuration files:
https://github.com/fl4p/fugu-mppt-firmware?tab=readme-ov-file#configuration

Also just pushed a mayor firmware update thats works with `esp-idf v5`.

Cheers
